name: Publish
run-name: Publish @sapphire/${{ inputs.package }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: The package to release
        required: true
        type: choice
        options:
          - async-queue
          - bitfield
          - cron
          - decorators
          - discord-utilities
          - discord.js-utilities
          - duration
          - eslint-config
          - eslint-plugin-result
          - event-iterator
          - fetch
          - iterator-utilities
          - lexure
          - node-utilities
          - phisherman
          - prettier-config
          - ratelimits
          - result
          - snowflake
          - stopwatch
          - string-store
          - time-utilities
          - timer-manager
          - timestamp
          - ts-config
          - utilities
      skip-automatic-bump:
        description: Whether to skip the automatic bumping of the packageversion
        required: false
        default: false
        type: boolean

jobs:
  PublishPackage:
    name: Publish @sapphire/${{ inputs.package}}
    uses: sapphiredev/.github/.github/workflows/reusable-publish.yml@main
    with:
      build: true
      project-name: '@sapphire/${{ inputs.package}}'
      working-directory: packages/${{ inputs.package }}
      skip-automatic-bump: ${{ inputs.skip-automatic-bump }}
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      SKYRA_TOKEN: ${{ secrets.SKYRA_TOKEN }}
